name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.4] # Placeholder, will be overridden by include
        laravel: [12.*] # Placeholder, will be overridden by include
        dependency-version: [prefer-stable]
        include:
          # Laravel 12
          - laravel: 12.*
            php: 8.4
            testbench: 10.*
            phpunit: ^11.0
          - laravel: 12.*
            php: 8.4
            testbench: 10.*
            phpunit: ^11.0
            dependency-version: prefer-lowest
          - laravel: 12.*
            php: 8.3
            testbench: 10.*
            phpunit: ^11.0
          - laravel: 12.*
            php: 8.2
            testbench: 10.*
            phpunit: ^11.0

          # Laravel 11
          - laravel: 11.*
            php: 8.4
            testbench: 9.*
            phpunit: ^11.0
          - laravel: 11.*
            php: 8.3
            testbench: 9.*
            phpunit: ^11.0
          - laravel: 11.*
            php: 8.2
            testbench: 9.*
            phpunit: ^11.0

          # Laravel 10
          - laravel: 10.*
            php: 8.3
            testbench: 8.*
            phpunit: ^10.0
          - laravel: 10.*
            php: 8.2
            testbench: 8.*
            phpunit: ^10.0
          - laravel: 10.*
            php: 8.1
            testbench: 8.*
            phpunit: ^10.0

          # Laravel 9
          - laravel: 9.*
            php: 8.2
            testbench: 7.*
            phpunit: ^9.3
          - laravel: 9.*
            php: 8.1
            testbench: 7.*
            phpunit: ^9.3
          - laravel: 9.*
            php: 8.0
            testbench: 7.*
            phpunit: ^9.3

          # Laravel 8
          - laravel: 8.*
            php: 8.1
            testbench: 6.*
            phpunit: ^9.3
          - laravel: 8.*
            php: 8.0
            testbench: 6.*
            phpunit: ^9.3
          - laravel: 8.*
            php: 7.4
            testbench: 6.*
            phpunit: ^9.3

          # Laravel 7
          - laravel: 7.*
            php: 8.0
            testbench: 5.*
            phpunit: ^9.3
          - laravel: 7.*
            php: 7.4
            testbench: 5.*
            phpunit: ^9.3

          # Laravel 6
          - laravel: 6.*
            php: 8.0
            testbench: 4.*
            phpunit: ^9.3
          - laravel: 6.*
            php: 7.4
            testbench: 4.*
            phpunit: ^9.3

          # Laravel 5.8
          - laravel: 5.8.*
            php: 7.4
            testbench: 3.8.*
            phpunit: ^7.5
          - laravel: 5.8.*
            php: 7.4
            testbench: 3.8.*
            phpunit: ^7.5
            dependency-version: prefer-lowest

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer config allow-plugins.kylekatarnls/update-helper true
          composer config audit.block-insecure false
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev -W
          if [ "$(php -r 'echo (int) (PHP_VERSION_ID < 80000);')" == "1" ]; then
            composer remove laravel/pint --dev --no-update
          fi
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
