name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3, 8.2, 8.1, 8.0, 7.4]
        laravel: [12.*, 11.*, 10.*, 9.*, 8.*, 7.*, 6.*, 5.8.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 12.*
            testbench: 10.*
            phpunit: ^11.0
          - laravel: 11.*
            testbench: 9.*
            phpunit: ^11.0
          - laravel: 10.*
            testbench: 8.*
            phpunit: ^10.0
          - laravel: 9.*
            testbench: 7.*
            phpunit: ^9.3
          - laravel: 8.*
            testbench: 6.*
            phpunit: ^9.3
          - laravel: 7.*
            testbench: 5.*
            phpunit: ^9.3
          - laravel: 6.*
            testbench: 4.*
            phpunit: ^9.3
          - laravel: 5.8.*
            testbench: 3.8.*
            phpunit: ^7.5
        exclude:
          # Laravel 11/12 compatibility
          - laravel: 12.*
            php: 8.1
          - laravel: 12.*
            php: 8.0
          - laravel: 12.*
            php: 7.4
          - laravel: 11.*
            php: 8.1
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 7.4
          # Laravel 10 compatibility
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4
          # Laravel 9 compatibility
          - laravel: 9.*
            php: 7.4
          # Laravel 5.8 compatibility (Ends at PHP 8.0)
          - laravel: 5.8.*
            php: 8.4
          - laravel: 5.8.*
            php: 8.3
          - laravel: 5.8.*
            php: 8.2
          - laravel: 5.8.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer config allow-plugins.kylekatarnls/update-helper true
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev -W
          if [ "$(php -r 'echo (int) (PHP_VERSION_ID < 80000);')" == "1" ]; then
            composer remove laravel/pint --dev --no-update
          fi
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
